# Generated by Django 4.1.1 on 2022-10-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='users_avatar/', verbose_name='Аватар')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Avatar Image',
                'verbose_name_plural': 'Avatar Images',
            },
        ),
    ]
